name: Build LoMo Android App Bundle

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug and Unzip
        run: |
          ls -R
          unzip -o "*.zip" -d .
          ls -R

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease
        env:
          NODE_OPTIONS: "--no-warnings"

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: lomo-aab
          path: app/build/outputs/bundle/release/*.aab
